 @startuml SecuenciaVehiculoCambiaVehiculo
' Caso de uso 
' Un auto atraviesa la ciudad y se encuentra con una Sorpresa Favorable. 

title Un vehiculo atraviesa la ciudad y se encuentra con una sorpresa Favorable. 


Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "auto:vehiculo" as vehiculo
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant "favorable:Favorable" as pozo

' participant "Direccion" as direccion
' participant "Modificador" as modificador

activate tablero


user -> tablero: mover(dir: Direccion)

activate vehiculo

tablero -> vehiculo: mover(dir: Direccion)

activate celda

vehiculo -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: vehiculo)

deactivate celda
activate pozo

calle -> pozo: cruzarCon(jug: vehiculo)

deactivate calle

pozo -> vehiculo: aplicarSorpresa(self)

vehiculo -> pozo: aplicarSorpresa(self.movimientos)
pozo --> vehiculo: self.movimientos = movimentosCalculados



deactivate pozo

deactivate calle
deactivate celda

user -> tablero: movimientos()
tablero -> vehiculo: movimientos()
vehiculo --> tablero: X * 0.8

deactivate vehiculo

tablero --> user: X * 0.8

deactivate tablero


@enduml

