@startuml SecuenciaMotoCambiaVehiculo
' Caso de uso 
' Una moto atraviesa la ciudad y se encuentra con un CambioDeVehiculo. Se cambia la moto por un auto.

title Una moto atraviesa la ciudad y se encuentra con un CambioDeVehiculo. Se cambia la moto por un auto.

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "moto:Moto" as vehiculo
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant ":CambioDeVehiculo" as cambioDeVehiculo
participant "auto:Auto" as nuevovehiculo

activate tablero

user -> tablero: mover(dir: Direccion)

activate vehiculo

tablero -> vehiculo: mover(dir: Direccion)

activate celda

vehiculo -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: vehiculo)

deactivate celda

activate cambioDeVehiculo

calle -> cambioDeVehiculo: cruzarCon(jug: vehiculo)

deactivate calle

cambioDeVehiculo -> vehiculo: aplicarModificador(self)

create nuevovehiculo

deactivate cambioDeVehiculo
vehiculo -> nuevovehiculo: <<create>>
activate nuevovehiculo
nuevovehiculo --> vehiculo: auto
vehiculo -> tablero: reemplazarVehiculo(auto)
vehiculo -> nuevovehiculo: asignarCeldaInicial(self.celda)
vehiculo -> nuevovehiculo: setDireccionActual(self.celda)
vehiculo -> nuevovehiculo: setMovimientos(self.celda)

deactivate vehiculo
nuevovehiculo -> nuevovehiculo: sumarMovimiento(1)


deactivate celda

user -> tablero: movimientos()

tablero -> nuevovehiculo: movimientos()
nuevovehiculo --> tablero: X + 1

deactivate nuevovehiculo

tablero --> user: X + 1

deactivate tablero


@enduml
