@startuml SecuenciaUnaMotoCruzaUnPozoYEsPenalizado
' Caso de uso 
' Una moto atraviesa la ciudad y se encuentra con un Pozo. Es penalizada en tres movimientos.

title Una moto atraviesa la ciudad y se encuentra con un Pozo. Es penalizada en tres movimientos.

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "moto:Moto" as vehiculo
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant "pozo:Pozo" as pozo

' participant "Direccion" as direccion
' participant "Modificador" as modificador

activate tablero


user -> tablero: mover(dir: Direccion)

activate vehiculo

tablero -> vehiculo: mover(dir: Direccion)

activate celda

vehiculo -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: vehiculo)

deactivate celda
activate pozo

calle -> pozo: cruzarCon(jug: vehiculo)

deactivate calle

pozo -> vehiculo: aplicarModificador(self)

vehiculo -> vehiculo: sumarMovimientos(self.penalizacion)

deactivate pozo

deactivate calle
deactivate celda

user -> tablero: movimientos()
tablero -> vehiculo: movimientos()
vehiculo --> tablero: X + 3

deactivate vehiculo

tablero --> user: X + 3

deactivate tablero


@enduml

